### ISSUE TITLE
Undefined offset

### ISSUE THREAD

**Issue by brianrc** [mt-support/tribe-ext-template-outliner#1]
Cool concept.

I get these literally everywhere tribe is, when I enable this plugin.
![firefox_RUw0gmEFhM](https://user-images.githubusercontent.com/573939/79635265-956f3600-81a2-11ea-8bf3-ed3cff71bf61.png)

Of course, I have a ton other plugins installed.

**Comment by cliffordp** [comment]
@bordoni, if you're available.

**Comment by cliffordp** [comment]
@brianrc Thanks for the detailed report. This extension is in active development (so ALL THE WARNINGS ;)
Once actually ready, we'll tag a release on GitHub and publish a new article at https://theeventscalendar.com/extensions/
